[app_servers]
app-server ansible_host=<EC2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/my-first-cicd-key.pem

[app_servers:vars]
app_directory=/home/ubuntu/my-first-cicd
app_port=3000
domain=yourdomain.com
email=admin@yourdomain.com